### ISSUE TITLE
datetime options not working in this extension

### ISSUE THREAD

**Issue by knyazhe1** [TheWatcher/InteractiveTimeline#2]
**min**,  **max**, **start** and **end** options not working instead on original examples. :disappointed_relieved:
because it has _string_ values only:
```javascript
			base.config = JSON.parse( mw.config.get( base.$el.attr( 'id' ) ) );
```
but options _datetime_ values need a make additional conversion! like as
```javascript
						 if ( startdate && body ) {
							 var event = { 'start': new Date( startdate ),
										   'content': body
										 };
```
otherwise min|max options can't right working in _links.Timeline.prototype.applyRange_ function of **timeline.js**

***hint:*** its working right in **vis** project :ok_hand:
```javascript
      max = (this.options.max != null) ? util.convert(this.options.max, 'Date').valueOf() : null,
      min = (this.options.min != null) ? util.convert(this.options.min, 'Date').valueOf() : null,
```

**Comment by TheWatcher** [comment]
Apologies for the delay, Life got in the way. I'm closing this as commit f06cbdaa6cbb77967fe9b9b10827eee0c37c344e implements a version of this, if it proves not to work correctly please reopen.
